# Soring, searching, and counting

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

In [3]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [2]:
x = np.array([[1,4],[3,1]])
print(np.sort(x, axis=1))


[[1 4]
 [1 3]]


Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [3]:
surnames =    np.array(['Hertz',    'Galilei', 'Hertz'])
first_names = np.array(['Heinrich', 'Galileo', 'Gustav'])

indices = np.lexsort((first_names, surnames))

print(indices)

[1 2 0]


Q3. Get the indices that would sort x along the second axis.

In [4]:
x = np.array([[1,4],[3,1]])
indices = np.argsort(x, axis=1)

print(indices)

[[0 1]
 [1 0]]


Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [6]:
x = np.random.permutation(10)
print ("x =", x)
print ("\nCheck the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5\n")
out = np.partition(x, 5)
print(out)

x = [8 6 4 9 5 7 1 3 0 2]

Check the fifth element of this new array is 5, the first four elements are all smaller than 5, and 6th through the end are bigger than 5

[1 2 4 0 3 5 7 6 9 8]


Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [9]:
x = np.random.permutation(10)
print("x =", x)

partitioned_indices = np.argpartition(x, 2)
print("partitioned_indices =", partitioned_indices)

x = [0 4 5 7 6 1 3 9 2 8]
partitioned_indices = [0 5 8 3 4 1 6 7 2 9]


## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [11]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)

print("maximum values =", np.amax(x, axis=1))
print("max indices =", np.argmax(x, axis=1))
print("minimum values =", np.amin(x, axis=1))
print("min indices =", np.argmin(x, axis=1))

x = [[6 5 0 7 2]
 [3 8 4 1 9]]
maximum values = [7 9]
max indices = [3 4]
minimum values = [0 1]
min indices = [2 3]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [13]:
x = np.array([[np.nan, 4], [3, 2]])

print("maximum values ignoring NaNs =", np.nanmax(x, axis=1))
print("max indices =", np.nanargmax(x, axis=1))
print("minimum values ignoring NaNs =", np.nanmin(x, axis=1))
print("min indices =", np.nanargmin(x, axis=1))

maximum values ignoring NaNs = [4. 3.]
max indices = [1 0]
minimum values ignoring NaNs = [4. 2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [14]:
x = np.array([[1, 2, 3], [1, 3, 5]])

values_bigger_than_2 = x[x > 2]
indices = np.where(x > 2)

print("Values bigger than 2 =", values_bigger_than_2)
print("Their indices are ", indices)

Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [15]:
x = np.array([[1, 2, 3], [1, 3, 5]])

indices = np.where(x.ravel() > 2)

print(indices)

(array([2, 4, 5], dtype=int64),)


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [16]:
x = np.arange(-5, 4).reshape(3, 3)

result = np.where(x < 0, 0, x)

print(result)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [18]:
x = np.array([1, 3, 5, 7, 9])
y = np.array([0, 4, 2, 6])

indices = np.searchsorted(x, y)

print(indices)

[0 2 1 3]


## Counting

Q12. Get the number of nonzero elements in x.

In [17]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
print(np.count_nonzero(x))

5
